// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAnkSM-H_yDuqro_Nv_8D2Jw21MNURYNM',
    appId: '1:187036775104:web:92d274b8913adb2b477325',
    messagingSenderId: '187036775104',
    projectId: 'socialnest-a6723',
    authDomain: 'socialnest-a6723.firebaseapp.com',
    storageBucket: 'socialnest-a6723.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfO8-raj419uzPDrk28ZcCoS4rNE2Ryt4',
    appId: '1:187036775104:android:eea631d374dab3d8477325',
    messagingSenderId: '187036775104',
    projectId: 'socialnest-a6723',
    storageBucket: 'socialnest-a6723.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9y_H7xi5GtaVc24WIkw8ITLtAHDfUgYc',
    appId: '1:187036775104:ios:d6f4373b081b98fa477325',
    messagingSenderId: '187036775104',
    projectId: 'socialnest-a6723',
    storageBucket: 'socialnest-a6723.firebasestorage.app',
    iosBundleId: 'com.socialnest.socialNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9y_H7xi5GtaVc24WIkw8ITLtAHDfUgYc',
    appId: '1:187036775104:ios:d6f4373b081b98fa477325',
    messagingSenderId: '187036775104',
    projectId: 'socialnest-a6723',
    storageBucket: 'socialnest-a6723.firebasestorage.app',
    iosBundleId: 'com.socialnest.socialNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAnkSM-H_yDuqro_Nv_8D2Jw21MNURYNM',
    appId: '1:187036775104:web:8a1a5f95ae6919b1477325',
    messagingSenderId: '187036775104',
    projectId: 'socialnest-a6723',
    authDomain: 'socialnest-a6723.firebaseapp.com',
    storageBucket: 'socialnest-a6723.firebasestorage.app',
  );
}
